services:
  postgres:
    container_name: postgres
    image: postgres:16.3-alpine
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgres/data
    networks:
      - polls

  redis:
    container_name: redis
    image: redis:7.2.4-alpine
    restart: always
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - polls

volumes:
  postgres_data:
  redis_data:

networks:
  polls:
